"""user db model

Revision ID: e1965d968808
Revises: 
Create Date: 2024-07-20 23:43:38.047894

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e1965d968808'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('USERS',
    sa.Column('id', sa.String(length=64), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(), nullable=True),
    sa.Column('last_active_at', sa.DateTime(), nullable=True),
    sa.Column('last_change_at', sa.DateTime(), nullable=True),
    sa.Column('failed_auth_at', sa.DateTime(), nullable=True),
    sa.Column('failed_auth_count', sa.Integer(), nullable=False),
    sa.Column('status', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_USERS_username'), ['username'], unique=True)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('ix_user_username')

    op.drop_table('user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', mysql.VARCHAR(length=64), nullable=False),
    sa.Column('username', mysql.VARCHAR(length=128), nullable=False),
    sa.Column('password', mysql.VARCHAR(length=256), nullable=False),
    sa.Column('role', mysql.VARCHAR(length=32), nullable=False),
    sa.Column('created_at', mysql.DATETIME(), nullable=False),
    sa.Column('expires_at', mysql.DATETIME(), nullable=False),
    sa.Column('last_login_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_active_at', mysql.DATETIME(), nullable=True),
    sa.Column('last_change_at', mysql.DATETIME(), nullable=True),
    sa.Column('failed_auth_at', mysql.DATETIME(), nullable=True),
    sa.Column('failed_auth_count', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('status', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('ix_user_username', ['username'], unique=True)

    with op.batch_alter_table('USERS', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_USERS_username'))

    op.drop_table('USERS')
    # ### end Alembic commands ###
